version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test
      - persist_to_workspace:
          root: .
          paths:
            - .

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run SonarQube Scan
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORGANIZATION"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORGANIZATION" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.token="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="." \
              -Dsonar.exclusions="node_modules/**" \
              -Dsonar.c.file.suffixes=- \
              -Dsonar.cpp.file.suffixes=- \
              -Dsonar.objc.file.suffixes=-

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - sonarqube:
          requires:
            - build
